language: ruby
rvm:
- 2.5.1
bundler_args: "--without production"
script:
- bundle exec rake db:create RAILS_ENV=test
- bundle exec rake db:migrate RAILS_ENV=test
- bundle exec rake test
branches:
  only:
  - master
deploy:
  provider: heroku
  api_key:
    secure: "f5Z8c+dzNYPyyAPYMul19VVmYWWI9HRe9y5oRv4Lp/K+MAdwscKSWocsgoCsJRdh5ZEGyQRvNUqg9JNnq2YVSZfoW32yGEFD7vCUwmOc4pLR9fhgRy8GkYGwO3CLbfm2TMO+lRWClY2oek3dBwk8L4r2LQi76KN6hUeXHIjpD7d5xOMjGtLNIbrEpEzTuqFZXyOjYtytqqFCyPp+R8T9WrI2Hb1YlELo3XIFMe0/bRYT0jzjwbzdMRJpCxeoppthRwNbEgU/cLXXtaGJjNCYJdnZbC6Hlneud0m5ykKaE9rQG8qyy+zaGQTZl0FpWM6msD7sWik2MlTVgkXGuXPjCGML/YO1Kh/kPeY34y0XK1GlptfIyzHMk8Gvt+C9FajyfHG/gsK/NlslUEB7DeVtPmMwtIFujG+TlVFD0girqK/95+eGs+hus8HAHlACr9kHNAhM7Q0m/wyLvuGd40y/yg+OTpAuUYc0zMFaY58U/d5geWFXOJoDl1IetN+OqyIZFTqnZ4QBjiWIN2S1e5mDfsXyz1bbBjt2tU2kwM+Od4zLl7MaiJiliNcJb8GJRv7XmTtKpTxT5m06mlILTAZO1c5z6DCTfxUGEOE7cdEKwzKqR2t965kdrtqv0CM3gqWNXsAepkuYG5ZdjpID9DQUVt2TK0JQBuVi+X12jmkQpyw="
  app: ideashub-api
  on: master
  run:
    - "rake db:drop"
    - "rake db:migrate"
    - "rake db:seed"
    - restart
