language: ruby
rvm:
  - 2.5.1

script:
 — bundle install --without production — jobs=3 — retry=3
 — bundle exec rake db:create
 — bundle exec rake db:migrate
 — bundle exec rspec

branches:
  only:
  - feature/travis-ci
